name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.300
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  
    - name: Add GPR Source using nuget.exe
      run: dotnet nuget sources update -name "github" -Source https://nuget.pkg.github.com/CRMNX-TEAM/index.json -Username ttkoma -Password ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: dotnet restore # --source nuget.org #--ignore-failed-sources
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack -c Release
    - name: Nuget push
      run: dotnet nuget push "bin/Release/*.nupkg" --source "github" --skip-duplicate
